### ISSUE TITLE
How to use it in iOS?

### ISSUE THREAD

**Issue by pirey** [guinatal/refreshgallery#1]
Hi, can I use this plugin on iOS?
I tried build my project and run it on simulator, but then I got the following error
`[4661:138193] ERROR: Plugin 'PluginRefreshGallery' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.`
The message says that I should check my plugin mapping in config.xml, but I have already put this `<gap:plugin name="com.guinatal.refreshgallery" />`

So what did I miss? Any help would be appreciated. Thank you.

**Comment by faridmv** [comment]
Hi,

Did you tried to use the following command to install this plugin?:

npm i cordova-plugin-refresh-gallery
